-- Additive catalogue migration. Existing order snapshots are never rewritten.
BEGIN;
CREATE TABLE IF NOT EXISTS catalog_products (
  slug text PRIMARY KEY CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  collection text NOT NULL CHECK (collection IN ('signature', 'tide')),
  stone text NOT NULL,
  price_cents integer NOT NULL CHECK (price_cents BETWEEN 100 AND 10000000),
  blurb text NOT NULL,
  description text NOT NULL,
  meaning text NOT NULL,
  story jsonb,
  images jsonb NOT NULL CHECK (jsonb_typeof(images) = 'array'),
  active boolean NOT NULL DEFAULT true,
  placeholder boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN 0 AND 9999),
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS catalog_product_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug text NOT NULL REFERENCES catalog_products(slug),
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (slug, version)
);

-- Never overwrite owner edits when this migration is run again.
INSERT INTO catalog_products (slug, sku, name, collection, stone, price_cents, blurb, description, meaning, story, images, active, placeholder, sort_order) VALUES
('new-beginnings', 'BFW-NEW-BEGINNINGS', 'New Beginnings Bracelet', 'signature', 'Moonstone + peridot', 6500, 'Moonstone and peridot, for a fresh start.', 'Genuine moonstone and peridot on a 14k gold-filled chain, finished with the signature lotus charm — made for the start of a new chapter.', 'Moonstone is the stone of new light and intuition; peridot carries renewal and growth. Together they mark a beginning rather than an arrival.', '{"title": "The first step", "paragraphs": ["A new chapter rarely arrives all at once. It is a job accepted before you feel ready, a box taped shut in an old apartment, a morning that starts differently from the one before it. This piece marks that moment — not the arrival, but the decision to go.", "Moonstone carries the light of beginnings; peridot has long been worn for renewal and growth. Together they read as hope with something solid underneath it. Finished with the lotus charm — a flower that opens out of the mud — on a waterproof 14k gold-filled chain made to be worn through whatever comes next."]}'::jsonb, '[{"src": "/products/new-beginnings/01.jpg", "kind": "photo"}, {"src": "/products/new-beginnings/02.jpg", "kind": "photo"}, {"src": "/products/new-beginnings/03.jpg", "kind": "photo"}, {"src": "/products/new-beginnings/04.jpg", "kind": "photo"}, {"src": "/products/new-beginnings/05.jpg", "kind": "photo"}, {"src": "/products/new-beginnings/06.jpg", "kind": "photo"}, {"src": "/products/new-beginnings/07.jpg", "kind": "graphic"}, {"src": "/products/new-beginnings/08.jpg", "kind": "graphic"}, {"src": "/products/new-beginnings/09.jpg", "kind": "graphic"}, {"src": "/products/new-beginnings/10.jpg", "kind": "graphic"}, {"src": "/products/new-beginnings/11.jpg", "kind": "graphic"}]'::jsonb, true, false, 0),
('pure-heart', 'BFW-PURE-HEART', 'Pure Heart Bracelet', 'signature', 'Rose quartz + peridot', 6500, 'Rose quartz and peridot — lead with warmth.', 'Genuine rose quartz and peridot on a fine 14k gold-filled chain with the signature lotus charm — a reminder that love begins within.', 'Rose quartz is worn for love and compassion, peridot for renewal and growth. Together they read as warmth with something new in it.', '{"title": "Love begins within", "paragraphs": ["Rose quartz is the stone people reach for when they want to be gentler — with someone else, or more often with themselves. Pure Heart takes that at face value. It is less about romance than about the decision to lead with warmth: made once, and then made again the next day.", "Soft pink rose quartz for love and compassion, green peridot for renewal set beside it so the piece never settles into sentiment. Both on a fine 14k gold-filled chain with the signature lotus charm — waterproof, and light enough to forget you are wearing."]}'::jsonb, '[{"src": "/products/pure-heart/01.jpg", "kind": "photo"}, {"src": "/products/pure-heart/02.jpg", "kind": "photo"}, {"src": "/products/pure-heart/03.jpg", "kind": "photo"}, {"src": "/products/pure-heart/04.jpg", "kind": "photo"}, {"src": "/products/pure-heart/05.jpg", "kind": "photo"}, {"src": "/products/pure-heart/06.jpg", "kind": "photo"}, {"src": "/products/pure-heart/07.jpg", "kind": "photo"}, {"src": "/products/pure-heart/08.jpg", "kind": "photo"}, {"src": "/products/pure-heart/09.jpg", "kind": "graphic"}, {"src": "/products/pure-heart/10.jpg", "kind": "graphic"}, {"src": "/products/pure-heart/11.jpg", "kind": "graphic"}, {"src": "/products/pure-heart/12.jpg", "kind": "graphic"}, {"src": "/products/pure-heart/13.jpg", "kind": "graphic"}]'::jsonb, true, false, 1),
('ocean-mist', 'BFW-OCEAN-MIST', 'Ocean Mist Bracelet', 'signature', 'Moonstone', 6500, 'Moonstone, for the calm of open water.', 'Genuine moonstone with clear quartz accents on premium 14k gold-filled — lightweight, waterproof, and inspired by the calm of the ocean.', 'Moonstone is worn for calm and intuition — a stone that holds light the way water does, without ever settling on a colour.', '{"title": "The colour of calm water", "paragraphs": ["Moonstone does what water does: hold light without ever settling on a colour. Turn it and a blue sheen moves under the surface, the way mist sits over the sea early in the morning, before the day has decided what it will be. Ocean Mist is built around that quiet.", "Genuine moonstone with clear quartz accents on premium 14k gold-filled, finished with the lotus charm. Lightweight and waterproof, and meant for ordinary days rather than special ones — the shower, the swim, the walk back."]}'::jsonb, '[{"src": "/products/ocean-mist/01.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/02.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/03.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/04.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/05.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/06.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/07.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/08.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/09.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/10.jpg", "kind": "photo"}, {"src": "/products/ocean-mist/11.jpg", "kind": "graphic"}, {"src": "/products/ocean-mist/12.jpg", "kind": "graphic"}, {"src": "/products/ocean-mist/13.jpg", "kind": "graphic"}, {"src": "/products/ocean-mist/14.jpg", "kind": "graphic"}]'::jsonb, true, false, 2),
('protection', 'BFW-PROTECTION', 'Protection Bracelet', 'signature', 'Black tourmaline + clear quartz', 6000, 'Black tourmaline and clear quartz. Stand rooted.', 'Genuine black tourmaline with clear quartz accents on a 14k gold-filled chain — grounding and protective, made for everyday wear.', 'Black tourmaline is traditionally worn for protection and grounding. Clear quartz sits alongside it for clarity — protection that does not mean hiding.', '{"title": "Stand rooted", "paragraphs": ["Some things are worth not moving for. Not arguing louder, not digging in out of stubbornness — just staying where you are because you know exactly why you are there. This piece was made for the people who hold that line quietly, and keep going anyway.", "Black tourmaline does the grounding; it has long been worn as a protective stone, the one kept close when the ground feels uncertain. Clear quartz is set between the dark beads to catch the light — protection that never asks you to hide. On a 1.7mm 14k gold-filled chain, waterproof and made to stay on, it is meant to be worn every day rather than saved for one."]}'::jsonb, '[{"src": "/products/protection/01.jpg", "kind": "photo"}, {"src": "/products/protection/02.jpg", "kind": "photo"}, {"src": "/products/protection/03.jpg", "kind": "photo"}, {"src": "/products/protection/04.jpg", "kind": "photo"}, {"src": "/products/protection/05.jpg", "kind": "photo"}, {"src": "/products/protection/06.jpg", "kind": "photo"}, {"src": "/products/protection/07.jpg", "kind": "photo"}, {"src": "/products/protection/08.jpg", "kind": "photo"}, {"src": "/products/protection/09.jpg", "kind": "photo"}, {"src": "/products/protection/10.jpg", "kind": "graphic"}, {"src": "/products/protection/11.jpg", "kind": "graphic"}, {"src": "/products/protection/12.jpg", "kind": "graphic"}, {"src": "/products/protection/13.jpg", "kind": "graphic"}]'::jsonb, true, false, 3),
('crystal-tide', 'BFW-CRYSTAL-TIDE', 'Crystal Tide Bracelet', 'signature', 'Peridot + clear quartz', 6500, 'Peridot and clear quartz, green through to clear.', 'Genuine peridot and clear quartz on premium 14k gold-filled — the meeting of earth and water, for the courage to begin again.', 'Peridot carries renewal and growth; clear quartz is worn for clarity and intention. Set together, they sharpen a fresh start rather than soften it.', '{"title": "Where the green goes clear", "paragraphs": ["Stand in shallow water on a bright day and you can watch the colour drain out of it. Close to shore it holds green — sand and light and weed all at once. A few steps further out it turns clear enough to read the stones on the bottom. Crystal Tide sets those two states beside each other.", "Peridot for renewal and growth, clear quartz for clarity and intention — the meeting of earth and water. On a 1.7mm 14k gold-filled chain, waterproof and made to stay on, it is a reminder to move through things with quiet confidence rather than certainty."]}'::jsonb, '[{"src": "/products/crystal-tide/01.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/02.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/03.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/04.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/05.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/06.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/07.jpg", "kind": "photo"}, {"src": "/products/crystal-tide/08.jpg", "kind": "graphic"}, {"src": "/products/crystal-tide/09.jpg", "kind": "graphic"}, {"src": "/products/crystal-tide/10.jpg", "kind": "graphic"}, {"src": "/products/crystal-tide/11.jpg", "kind": "graphic"}, {"src": "/products/crystal-tide/12.jpg", "kind": "photo"}]'::jsonb, true, false, 4),
('quiet-strength', 'BFW-QUIET-STRENGTH', 'Quiet Strength Bracelet', 'signature', 'Black tourmaline', 5500, 'Three tourmaline beads. Nothing else needed.', 'Genuine black tourmaline set sparely on a premium 14k gold-filled chain — lightweight, waterproof, and quietly grounding.', 'Black tourmaline is traditionally worn for grounding — the stone kept close when you need to stay level.', '{"title": "It doesn''t need to be loud", "paragraphs": ["Three black beads on a plain gold chain. No stack, no statement, nothing that asks to be noticed from across a room. That restraint is the entire point — some of the strongest people you know have never once raised their voice about it.", "Black tourmaline is traditionally worn for grounding: the stone kept close when you need to stay level. Set this sparely on a 14k gold-filled chain, waterproof and made for daily wear, it is the least decorative piece in the collection and the most deliberate."]}'::jsonb, '[{"src": "/products/quiet-strength/01.jpg", "kind": "photo"}, {"src": "/products/quiet-strength/02.jpg", "kind": "photo"}, {"src": "/products/quiet-strength/03.jpg", "kind": "photo"}, {"src": "/products/quiet-strength/04.jpg", "kind": "photo"}, {"src": "/products/quiet-strength/05.jpg", "kind": "photo"}, {"src": "/products/quiet-strength/06.jpg", "kind": "graphic"}, {"src": "/products/quiet-strength/07.jpg", "kind": "graphic"}, {"src": "/products/quiet-strength/08.jpg", "kind": "graphic"}, {"src": "/products/quiet-strength/09.jpg", "kind": "graphic"}]'::jsonb, true, false, 5),
('peridot-tide', 'BFW-PERIDOT-TIDE', 'Peridot Tide', 'tide', 'Peridot + freshwater pearl', 4900, 'One luminous pearl. Three vibrant peridot gemstones. Your tide.', 'A delicate, lightweight bracelet inspired by the movement and renewal of the tide. Handcrafted in Canada with a 14K gold-filled chain and findings, one freshwater pearl, and three genuine faceted peridot gemstones in the intentionally asymmetric design of the Tide Collection.', 'The birthstone of August, peridot is traditionally associated with renewal, positivity, and new beginnings — a reminder that every tide brings the possibility of renewal.', NULL, '[{"src": "/products/peridot-tide/01.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/02.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/03.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/04.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/05.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/06.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/07.jpg", "kind": "photo"}, {"src": "/products/peridot-tide/08.jpg", "kind": "photo"}]'::jsonb, true, false, 6),
('aquamarine-tide', 'BFW-AQUAMARINE-TIDE', 'Aquamarine Tide', 'tide', 'Aquamarine + freshwater pearl', 4900, 'One luminous pearl. Three serene aquamarine gemstones. Your tide.', 'A delicate, lightweight bracelet inspired by the ever-changing rhythm of the tide. Handcrafted in Canada with a 14K gold-filled chain and findings, one freshwater pearl, and three genuine faceted aquamarine gemstones in the intentionally asymmetric design of the Tide Collection.', 'The birthstone of March, aquamarine is traditionally associated with calm, clarity, and the sea — a meaningful everyday piece in the soft blue colour of water.', NULL, '[{"src": "/products/aquamarine-tide/01.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/02.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/03.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/04.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/05.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/06.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/07.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/08.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/09.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/10.jpg", "kind": "photo"}, {"src": "/products/aquamarine-tide/11.jpg", "kind": "photo"}]'::jsonb, true, false, 7),
('amethyst-tide', 'BFW-AMETHYST-TIDE', 'Amethyst Tide', 'tide', 'Amethyst + freshwater pearl', 4900, 'One luminous pearl. Three natural amethyst gemstones. Your tide.', 'A delicate, lightweight bracelet inspired by the rhythm of the tide. Handcrafted in Canada with a 14K gold-filled chain and findings, one freshwater pearl, and three genuine faceted amethyst gemstones in the intentionally asymmetric design of the Tide Collection.', 'Amethyst is traditionally associated with calm, clarity, and inner peace, bringing a soft touch of purple to this everyday piece.', NULL, '[{"src": "/products/amethyst-tide/01.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/02.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/03.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/04.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/05.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/06.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/07.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/08.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/09.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/10.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/11.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/12.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/13.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/14.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/15.jpg", "kind": "photo"}, {"src": "/products/amethyst-tide/16.jpg", "kind": "photo"}]'::jsonb, true, false, 8)
ON CONFLICT (slug) DO NOTHING;
COMMIT;
